name = "CREAMext"
uuid = "6b848077-5ff2-4d64-ac86-18d0da6de843"
authors = ["ConnectedSystems"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
Conda = "1.10.2"
RCall = "0.14.6"
